# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='handle',
        ),
        migrations.AddField(
            model_name='tip',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('c#', 'C#'), ('c++', 'C++'), ('delphi', 'Delphi'), ('go', 'Go'), ('haskell', 'Haskell'), ('java', 'Java'), ('javascript', 'Javascript'), ('kotlin', 'Kotlin'), ('lua', 'lua'), ('matlab', 'Matlab'), ('objective-c', 'Objective-C'), ('perl', 'Perl'), ('php', 'PHP'), ('python', 'Python'), ('r', 'R'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('scala', 'Scala'), ('swift', 'Swift'), ('typescript', 'TypeScript'), ('vba', 'VBA'), ('visual', 'Visual')], default='python', max_length=15),
        ),
    ]
